### ISSUE TITLE
IO Exception "Reason cookie store unavailable: :hash"

### ISSUE THREAD

**Issue by lilith** [chargebee/chargebee-ruby#47]
I'm encountering the following error. Not sure whether it's an API or client issue. 
```
IO Exception when trying to connect to chargebee with url https://imazen.chargebee.com/api/v2/subscriptions/[redacted] . Reason cookie store unavailable: :hash
/app/vendor/bundle/ruby/2.5.0/bundler/gems/chargebee-ruby-143900d4d74f/lib/chargebee/rest.rb:53:in `rescue in request'
/app/vendor/bundle/ruby/2.5.0/bundler/gems/chargebee-ruby-143900d4d74f/lib/chargebee/rest.rb:44:in `request'
/app/vendor/bundle/ruby/2.5.0/bundler/gems/chargebee-ruby-143900d4d74f/lib/chargebee/request.rb:18:in `send'
/app/vendor/bundle/ruby/2.5.0/bundler/gems/chargebee-ruby-143900d4d74f/lib/chargebee/models/subscription.rb:44:in `retrieve'
```

**Comment by cb-sriramthiagarajan** [comment]
Hi @lilith, I'm sorry for the delayed response.

Can you please let us know if you're still facing this issue? This is working fine for us in the latest version of the SDK.

**Comment by cb-alish** [comment]
Closing this issue as we've moved from rest-client to native `Net::HTTP` since `v2.49.0`. Sorry for the delay in execution. Please feel free to reopen or post in the issue section if you encounter any problems.
